
name: CI/CI Mini Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
  gi
steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 1.8
    uses: actions/setup-java@v3
    with:
      java-version: '19'
      distribution: 'temurin'
      cache: maven
  - name: Run Automation
    run: mvn clean verify
